// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/chronicle_confidence.fbs".

#pragma once

#include "../datatypes/float32.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Confidence score (0.0 to 1.0) for a Chronicle event link.
    ///
    /// Controls visual opacity of link arcs in the ChronicleTimelineView.
    struct ChronicleConfidence {
        rerun::datatypes::Float32 value;

      public:
        ChronicleConfidence() = default;

        ChronicleConfidence(rerun::datatypes::Float32 value_) : value(value_) {}

        ChronicleConfidence& operator=(rerun::datatypes::Float32 value_) {
            value = value_;
            return *this;
        }

        ChronicleConfidence(float value_) : value(value_) {}

        ChronicleConfidence& operator=(float value_) {
            value = value_;
            return *this;
        }

        /// Cast to the underlying Float32 datatype
        operator rerun::datatypes::Float32() const {
            return value;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::Float32) == sizeof(components::ChronicleConfidence));

    /// \private
    template <>
    struct Loggable<components::ChronicleConfidence> {
        static constexpr std::string_view ComponentType = "rerun.components.ChronicleConfidence";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::Float32>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::ChronicleConfidence` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::ChronicleConfidence* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::Float32>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::Float32>::to_arrow(
                    &instances->value,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
