// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/chronicle_entity_id.fbs".

#pragma once

#include "../datatypes/utf8.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>
#include <string>
#include <utility>

namespace rerun::components {
    /// **Component**: The ID of a Chronicle entity (e.g. "cust_123", "tkt_456", "sess_789").
    struct ChronicleEntityId {
        rerun::datatypes::Utf8 value;

      public:
        ChronicleEntityId() = default;

        ChronicleEntityId(rerun::datatypes::Utf8 value_) : value(std::move(value_)) {}

        ChronicleEntityId& operator=(rerun::datatypes::Utf8 value_) {
            value = std::move(value_);
            return *this;
        }

        ChronicleEntityId(std::string value_) : value(std::move(value_)) {}

        ChronicleEntityId& operator=(std::string value_) {
            value = std::move(value_);
            return *this;
        }

        /// Cast to the underlying Utf8 datatype
        operator rerun::datatypes::Utf8() const {
            return value;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::Utf8) == sizeof(components::ChronicleEntityId));

    /// \private
    template <>
    struct Loggable<components::ChronicleEntityId> {
        static constexpr std::string_view ComponentType = "rerun.components.ChronicleEntityId";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::Utf8>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::ChronicleEntityId` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::ChronicleEntityId* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::Utf8>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::Utf8>::to_arrow(&instances->value, num_instances);
            }
        }
    };
} // namespace rerun
