// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/chronicle_event.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/chronicle_event_type.hpp"
#include "../components/chronicle_payload.hpp"
#include "../components/chronicle_source.hpp"
#include "../components/chronicle_topic.hpp"
#include "../components/color.hpp"
#include "../components/text.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::archetypes {
    /// **Archetype**: A Chronicle SaaS event with source, type, and optional JSON payload.
    ///
    /// Events are the core data type in Chronicle. Each event represents a
    /// single occurrence from a SaaS source (e.g. a Stripe payment, a support
    /// ticket, a product page view). Events are logged at entity paths that
    /// encode the entity hierarchy: `/{org}/{entity_type}/{entity_id}/{source}/{event_type}`.
    struct ChronicleEvent {
        /// The data source (e.g. "stripe", "support", "product", "marketing").
        std::optional<ComponentBatch> source;

        /// The event type (e.g. "payment_intent.succeeded", "ticket.created").
        std::optional<ComponentBatch> event_type;

        /// The topic/category (e.g. "payments", "tickets", "usage").
        std::optional<ComponentBatch> topic;

        /// JSON payload serialized as a string.
        std::optional<ComponentBatch> payload;

        /// Optional color for the event marker.
        std::optional<ComponentBatch> color;

        /// Optional text label.
        std::optional<ComponentBatch> label;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.archetypes.ChronicleEvent";

        /// `ComponentDescriptor` for the `source` field.
        static constexpr auto Descriptor_source = ComponentDescriptor(
            ArchetypeName, "ChronicleEvent:source",
            Loggable<rerun::components::ChronicleSource>::ComponentType
        );
        /// `ComponentDescriptor` for the `event_type` field.
        static constexpr auto Descriptor_event_type = ComponentDescriptor(
            ArchetypeName, "ChronicleEvent:event_type",
            Loggable<rerun::components::ChronicleEventType>::ComponentType
        );
        /// `ComponentDescriptor` for the `topic` field.
        static constexpr auto Descriptor_topic = ComponentDescriptor(
            ArchetypeName, "ChronicleEvent:topic",
            Loggable<rerun::components::ChronicleTopic>::ComponentType
        );
        /// `ComponentDescriptor` for the `payload` field.
        static constexpr auto Descriptor_payload = ComponentDescriptor(
            ArchetypeName, "ChronicleEvent:payload",
            Loggable<rerun::components::ChroniclePayload>::ComponentType
        );
        /// `ComponentDescriptor` for the `color` field.
        static constexpr auto Descriptor_color = ComponentDescriptor(
            ArchetypeName, "ChronicleEvent:color", Loggable<rerun::components::Color>::ComponentType
        );
        /// `ComponentDescriptor` for the `label` field.
        static constexpr auto Descriptor_label = ComponentDescriptor(
            ArchetypeName, "ChronicleEvent:label", Loggable<rerun::components::Text>::ComponentType
        );

      public:
        ChronicleEvent() = default;
        ChronicleEvent(ChronicleEvent&& other) = default;
        ChronicleEvent(const ChronicleEvent& other) = default;
        ChronicleEvent& operator=(const ChronicleEvent& other) = default;
        ChronicleEvent& operator=(ChronicleEvent&& other) = default;

        explicit ChronicleEvent(
            rerun::components::ChronicleSource _source,
            rerun::components::ChronicleEventType _event_type
        )
            : source(
                  ComponentBatch::from_loggable(std::move(_source), Descriptor_source)
                      .value_or_throw()
              ),
              event_type(
                  ComponentBatch::from_loggable(std::move(_event_type), Descriptor_event_type)
                      .value_or_throw()
              ) {}

        /// Update only some specific fields of a `ChronicleEvent`.
        static ChronicleEvent update_fields() {
            return ChronicleEvent();
        }

        /// Clear all the fields of a `ChronicleEvent`.
        static ChronicleEvent clear_fields();

        /// The data source (e.g. "stripe", "support", "product", "marketing").
        ChronicleEvent with_source(const rerun::components::ChronicleSource& _source) && {
            source = ComponentBatch::from_loggable(_source, Descriptor_source).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `source` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_source` should
        /// be used when logging a single row's worth of data.
        ChronicleEvent with_many_source(
            const Collection<rerun::components::ChronicleSource>& _source
        ) && {
            source = ComponentBatch::from_loggable(_source, Descriptor_source).value_or_throw();
            return std::move(*this);
        }

        /// The event type (e.g. "payment_intent.succeeded", "ticket.created").
        ChronicleEvent with_event_type(
            const rerun::components::ChronicleEventType& _event_type
        ) && {
            event_type =
                ComponentBatch::from_loggable(_event_type, Descriptor_event_type).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `event_type` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_event_type` should
        /// be used when logging a single row's worth of data.
        ChronicleEvent with_many_event_type(
            const Collection<rerun::components::ChronicleEventType>& _event_type
        ) && {
            event_type =
                ComponentBatch::from_loggable(_event_type, Descriptor_event_type).value_or_throw();
            return std::move(*this);
        }

        /// The topic/category (e.g. "payments", "tickets", "usage").
        ChronicleEvent with_topic(const rerun::components::ChronicleTopic& _topic) && {
            topic = ComponentBatch::from_loggable(_topic, Descriptor_topic).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `topic` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_topic` should
        /// be used when logging a single row's worth of data.
        ChronicleEvent with_many_topic(
            const Collection<rerun::components::ChronicleTopic>& _topic
        ) && {
            topic = ComponentBatch::from_loggable(_topic, Descriptor_topic).value_or_throw();
            return std::move(*this);
        }

        /// JSON payload serialized as a string.
        ChronicleEvent with_payload(const rerun::components::ChroniclePayload& _payload) && {
            payload = ComponentBatch::from_loggable(_payload, Descriptor_payload).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `payload` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_payload` should
        /// be used when logging a single row's worth of data.
        ChronicleEvent with_many_payload(
            const Collection<rerun::components::ChroniclePayload>& _payload
        ) && {
            payload = ComponentBatch::from_loggable(_payload, Descriptor_payload).value_or_throw();
            return std::move(*this);
        }

        /// Optional color for the event marker.
        ChronicleEvent with_color(const rerun::components::Color& _color) && {
            color = ComponentBatch::from_loggable(_color, Descriptor_color).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `color` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_color` should
        /// be used when logging a single row's worth of data.
        ChronicleEvent with_many_color(const Collection<rerun::components::Color>& _color) && {
            color = ComponentBatch::from_loggable(_color, Descriptor_color).value_or_throw();
            return std::move(*this);
        }

        /// Optional text label.
        ChronicleEvent with_label(const rerun::components::Text& _label) && {
            label = ComponentBatch::from_loggable(_label, Descriptor_label).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `label` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_label` should
        /// be used when logging a single row's worth of data.
        ChronicleEvent with_many_label(const Collection<rerun::components::Text>& _label) && {
            label = ComponentBatch::from_loggable(_label, Descriptor_label).value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::ChronicleEvent> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(
            const archetypes::ChronicleEvent& archetype
        );
    };
} // namespace rerun
