// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/chronicle_entity_ref.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/chronicle_entity_id.hpp"
#include "../components/chronicle_entity_type.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::archetypes {
    /// **Archetype**: An entity reference associating a Chronicle event with a typed entity.
    ///
    /// Entity refs are the many-to-many mapping between events and entities
    /// (e.g. linking an event to customer "cust_123" and ticket "tkt_456").
    /// Logged as a component on the event entity path.
    struct ChronicleEntityRef {
        /// The type of the referenced entity (e.g. "customer", "account", "ticket").
        std::optional<ComponentBatch> entity_type;

        /// The ID of the referenced entity (e.g. "cust_123", "tkt_456").
        std::optional<ComponentBatch> entity_id;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.archetypes.ChronicleEntityRef";

        /// `ComponentDescriptor` for the `entity_type` field.
        static constexpr auto Descriptor_entity_type = ComponentDescriptor(
            ArchetypeName, "ChronicleEntityRef:entity_type",
            Loggable<rerun::components::ChronicleEntityType>::ComponentType
        );
        /// `ComponentDescriptor` for the `entity_id` field.
        static constexpr auto Descriptor_entity_id = ComponentDescriptor(
            ArchetypeName, "ChronicleEntityRef:entity_id",
            Loggable<rerun::components::ChronicleEntityId>::ComponentType
        );

      public:
        ChronicleEntityRef() = default;
        ChronicleEntityRef(ChronicleEntityRef&& other) = default;
        ChronicleEntityRef(const ChronicleEntityRef& other) = default;
        ChronicleEntityRef& operator=(const ChronicleEntityRef& other) = default;
        ChronicleEntityRef& operator=(ChronicleEntityRef&& other) = default;

        explicit ChronicleEntityRef(
            rerun::components::ChronicleEntityType _entity_type,
            rerun::components::ChronicleEntityId _entity_id
        )
            : entity_type(
                  ComponentBatch::from_loggable(std::move(_entity_type), Descriptor_entity_type)
                      .value_or_throw()
              ),
              entity_id(
                  ComponentBatch::from_loggable(std::move(_entity_id), Descriptor_entity_id)
                      .value_or_throw()
              ) {}

        /// Update only some specific fields of a `ChronicleEntityRef`.
        static ChronicleEntityRef update_fields() {
            return ChronicleEntityRef();
        }

        /// Clear all the fields of a `ChronicleEntityRef`.
        static ChronicleEntityRef clear_fields();

        /// The type of the referenced entity (e.g. "customer", "account", "ticket").
        ChronicleEntityRef with_entity_type(
            const rerun::components::ChronicleEntityType& _entity_type
        ) && {
            entity_type = ComponentBatch::from_loggable(_entity_type, Descriptor_entity_type)
                              .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `entity_type` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_entity_type` should
        /// be used when logging a single row's worth of data.
        ChronicleEntityRef with_many_entity_type(
            const Collection<rerun::components::ChronicleEntityType>& _entity_type
        ) && {
            entity_type = ComponentBatch::from_loggable(_entity_type, Descriptor_entity_type)
                              .value_or_throw();
            return std::move(*this);
        }

        /// The ID of the referenced entity (e.g. "cust_123", "tkt_456").
        ChronicleEntityRef with_entity_id(
            const rerun::components::ChronicleEntityId& _entity_id
        ) && {
            entity_id =
                ComponentBatch::from_loggable(_entity_id, Descriptor_entity_id).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `entity_id` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_entity_id` should
        /// be used when logging a single row's worth of data.
        ChronicleEntityRef with_many_entity_id(
            const Collection<rerun::components::ChronicleEntityId>& _entity_id
        ) && {
            entity_id =
                ComponentBatch::from_loggable(_entity_id, Descriptor_entity_id).value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::ChronicleEntityRef> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(
            const archetypes::ChronicleEntityRef& archetype
        );
    };
} // namespace rerun
