// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/chronicle_link.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/chronicle_confidence.hpp"
#include "../components/chronicle_link_type.hpp"
#include "../components/chronicle_reasoning.hpp"
#include "../components/chronicle_source_event.hpp"
#include "../components/chronicle_target_event.hpp"
#include "../components/color.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::archetypes {
    /// **Archetype**: A causal or relational link between two Chronicle events.
    ///
    /// Links represent directed edges in the event graph (e.g. "payment failure
    /// caused support ticket"). They are rendered as Bezier arcs in the
    /// ChronicleTimelineView.
    struct ChronicleLink {
        /// Entity path of the source event.
        std::optional<ComponentBatch> source_event;

        /// Entity path of the target event.
        std::optional<ComponentBatch> target_event;

        /// Type of the link (e.g. "caused_by", "led_to", "triggered", "related_to").
        std::optional<ComponentBatch> link_type;

        /// Confidence score (0.0 to 1.0). Controls arc opacity in the viewer.
        std::optional<ComponentBatch> confidence;

        /// Human-readable reasoning for why this link exists.
        std::optional<ComponentBatch> reasoning;

        /// Optional color override for the link arc.
        std::optional<ComponentBatch> color;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.archetypes.ChronicleLink";

        /// `ComponentDescriptor` for the `source_event` field.
        static constexpr auto Descriptor_source_event = ComponentDescriptor(
            ArchetypeName, "ChronicleLink:source_event",
            Loggable<rerun::components::ChronicleSourceEvent>::ComponentType
        );
        /// `ComponentDescriptor` for the `target_event` field.
        static constexpr auto Descriptor_target_event = ComponentDescriptor(
            ArchetypeName, "ChronicleLink:target_event",
            Loggable<rerun::components::ChronicleTargetEvent>::ComponentType
        );
        /// `ComponentDescriptor` for the `link_type` field.
        static constexpr auto Descriptor_link_type = ComponentDescriptor(
            ArchetypeName, "ChronicleLink:link_type",
            Loggable<rerun::components::ChronicleLinkType>::ComponentType
        );
        /// `ComponentDescriptor` for the `confidence` field.
        static constexpr auto Descriptor_confidence = ComponentDescriptor(
            ArchetypeName, "ChronicleLink:confidence",
            Loggable<rerun::components::ChronicleConfidence>::ComponentType
        );
        /// `ComponentDescriptor` for the `reasoning` field.
        static constexpr auto Descriptor_reasoning = ComponentDescriptor(
            ArchetypeName, "ChronicleLink:reasoning",
            Loggable<rerun::components::ChronicleReasoning>::ComponentType
        );
        /// `ComponentDescriptor` for the `color` field.
        static constexpr auto Descriptor_color = ComponentDescriptor(
            ArchetypeName, "ChronicleLink:color", Loggable<rerun::components::Color>::ComponentType
        );

      public:
        ChronicleLink() = default;
        ChronicleLink(ChronicleLink&& other) = default;
        ChronicleLink(const ChronicleLink& other) = default;
        ChronicleLink& operator=(const ChronicleLink& other) = default;
        ChronicleLink& operator=(ChronicleLink&& other) = default;

        explicit ChronicleLink(
            rerun::components::ChronicleSourceEvent _source_event,
            rerun::components::ChronicleTargetEvent _target_event,
            rerun::components::ChronicleLinkType _link_type
        )
            : source_event(
                  ComponentBatch::from_loggable(std::move(_source_event), Descriptor_source_event)
                      .value_or_throw()
              ),
              target_event(
                  ComponentBatch::from_loggable(std::move(_target_event), Descriptor_target_event)
                      .value_or_throw()
              ),
              link_type(
                  ComponentBatch::from_loggable(std::move(_link_type), Descriptor_link_type)
                      .value_or_throw()
              ) {}

        /// Update only some specific fields of a `ChronicleLink`.
        static ChronicleLink update_fields() {
            return ChronicleLink();
        }

        /// Clear all the fields of a `ChronicleLink`.
        static ChronicleLink clear_fields();

        /// Entity path of the source event.
        ChronicleLink with_source_event(
            const rerun::components::ChronicleSourceEvent& _source_event
        ) && {
            source_event = ComponentBatch::from_loggable(_source_event, Descriptor_source_event)
                               .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `source_event` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_source_event` should
        /// be used when logging a single row's worth of data.
        ChronicleLink with_many_source_event(
            const Collection<rerun::components::ChronicleSourceEvent>& _source_event
        ) && {
            source_event = ComponentBatch::from_loggable(_source_event, Descriptor_source_event)
                               .value_or_throw();
            return std::move(*this);
        }

        /// Entity path of the target event.
        ChronicleLink with_target_event(
            const rerun::components::ChronicleTargetEvent& _target_event
        ) && {
            target_event = ComponentBatch::from_loggable(_target_event, Descriptor_target_event)
                               .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `target_event` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_target_event` should
        /// be used when logging a single row's worth of data.
        ChronicleLink with_many_target_event(
            const Collection<rerun::components::ChronicleTargetEvent>& _target_event
        ) && {
            target_event = ComponentBatch::from_loggable(_target_event, Descriptor_target_event)
                               .value_or_throw();
            return std::move(*this);
        }

        /// Type of the link (e.g. "caused_by", "led_to", "triggered", "related_to").
        ChronicleLink with_link_type(const rerun::components::ChronicleLinkType& _link_type) && {
            link_type =
                ComponentBatch::from_loggable(_link_type, Descriptor_link_type).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `link_type` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_link_type` should
        /// be used when logging a single row's worth of data.
        ChronicleLink with_many_link_type(
            const Collection<rerun::components::ChronicleLinkType>& _link_type
        ) && {
            link_type =
                ComponentBatch::from_loggable(_link_type, Descriptor_link_type).value_or_throw();
            return std::move(*this);
        }

        /// Confidence score (0.0 to 1.0). Controls arc opacity in the viewer.
        ChronicleLink with_confidence(
            const rerun::components::ChronicleConfidence& _confidence
        ) && {
            confidence =
                ComponentBatch::from_loggable(_confidence, Descriptor_confidence).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `confidence` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_confidence` should
        /// be used when logging a single row's worth of data.
        ChronicleLink with_many_confidence(
            const Collection<rerun::components::ChronicleConfidence>& _confidence
        ) && {
            confidence =
                ComponentBatch::from_loggable(_confidence, Descriptor_confidence).value_or_throw();
            return std::move(*this);
        }

        /// Human-readable reasoning for why this link exists.
        ChronicleLink with_reasoning(const rerun::components::ChronicleReasoning& _reasoning) && {
            reasoning =
                ComponentBatch::from_loggable(_reasoning, Descriptor_reasoning).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `reasoning` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_reasoning` should
        /// be used when logging a single row's worth of data.
        ChronicleLink with_many_reasoning(
            const Collection<rerun::components::ChronicleReasoning>& _reasoning
        ) && {
            reasoning =
                ComponentBatch::from_loggable(_reasoning, Descriptor_reasoning).value_or_throw();
            return std::move(*this);
        }

        /// Optional color override for the link arc.
        ChronicleLink with_color(const rerun::components::Color& _color) && {
            color = ComponentBatch::from_loggable(_color, Descriptor_color).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `color` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_color` should
        /// be used when logging a single row's worth of data.
        ChronicleLink with_many_color(const Collection<rerun::components::Color>& _color) && {
            color = ComponentBatch::from_loggable(_color, Descriptor_color).value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::ChronicleLink> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(
            const archetypes::ChronicleLink& archetype
        );
    };
} // namespace rerun
