// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/chronicle_entity_ref.fbs".

#include "chronicle_entity_ref.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    ChronicleEntityRef ChronicleEntityRef::clear_fields() {
        auto archetype = ChronicleEntityRef();
        archetype.entity_type =
            ComponentBatch::empty<rerun::components::ChronicleEntityType>(Descriptor_entity_type)
                .value_or_throw();
        archetype.entity_id =
            ComponentBatch::empty<rerun::components::ChronicleEntityId>(Descriptor_entity_id)
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> ChronicleEntityRef::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(2);
        if (entity_type.has_value()) {
            columns.push_back(entity_type.value().partitioned(lengths_).value_or_throw());
        }
        if (entity_id.has_value()) {
            columns.push_back(entity_id.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> ChronicleEntityRef::columns() {
        if (entity_type.has_value()) {
            return columns(std::vector<uint32_t>(entity_type.value().length(), 1));
        }
        if (entity_id.has_value()) {
            return columns(std::vector<uint32_t>(entity_id.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::ChronicleEntityRef>::as_batches(
        const archetypes::ChronicleEntityRef& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(2);

        if (archetype.entity_type.has_value()) {
            cells.push_back(archetype.entity_type.value());
        }
        if (archetype.entity_id.has_value()) {
            cells.push_back(archetype.entity_id.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
