// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/chronicle_link.fbs".

#include "chronicle_link.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    ChronicleLink ChronicleLink::clear_fields() {
        auto archetype = ChronicleLink();
        archetype.source_event =
            ComponentBatch::empty<rerun::components::ChronicleSourceEvent>(Descriptor_source_event)
                .value_or_throw();
        archetype.target_event =
            ComponentBatch::empty<rerun::components::ChronicleTargetEvent>(Descriptor_target_event)
                .value_or_throw();
        archetype.link_type =
            ComponentBatch::empty<rerun::components::ChronicleLinkType>(Descriptor_link_type)
                .value_or_throw();
        archetype.confidence =
            ComponentBatch::empty<rerun::components::ChronicleConfidence>(Descriptor_confidence)
                .value_or_throw();
        archetype.reasoning =
            ComponentBatch::empty<rerun::components::ChronicleReasoning>(Descriptor_reasoning)
                .value_or_throw();
        archetype.color =
            ComponentBatch::empty<rerun::components::Color>(Descriptor_color).value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> ChronicleLink::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(6);
        if (source_event.has_value()) {
            columns.push_back(source_event.value().partitioned(lengths_).value_or_throw());
        }
        if (target_event.has_value()) {
            columns.push_back(target_event.value().partitioned(lengths_).value_or_throw());
        }
        if (link_type.has_value()) {
            columns.push_back(link_type.value().partitioned(lengths_).value_or_throw());
        }
        if (confidence.has_value()) {
            columns.push_back(confidence.value().partitioned(lengths_).value_or_throw());
        }
        if (reasoning.has_value()) {
            columns.push_back(reasoning.value().partitioned(lengths_).value_or_throw());
        }
        if (color.has_value()) {
            columns.push_back(color.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> ChronicleLink::columns() {
        if (source_event.has_value()) {
            return columns(std::vector<uint32_t>(source_event.value().length(), 1));
        }
        if (target_event.has_value()) {
            return columns(std::vector<uint32_t>(target_event.value().length(), 1));
        }
        if (link_type.has_value()) {
            return columns(std::vector<uint32_t>(link_type.value().length(), 1));
        }
        if (confidence.has_value()) {
            return columns(std::vector<uint32_t>(confidence.value().length(), 1));
        }
        if (reasoning.has_value()) {
            return columns(std::vector<uint32_t>(reasoning.value().length(), 1));
        }
        if (color.has_value()) {
            return columns(std::vector<uint32_t>(color.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::ChronicleLink>::as_batches(
        const archetypes::ChronicleLink& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(6);

        if (archetype.source_event.has_value()) {
            cells.push_back(archetype.source_event.value());
        }
        if (archetype.target_event.has_value()) {
            cells.push_back(archetype.target_event.value());
        }
        if (archetype.link_type.has_value()) {
            cells.push_back(archetype.link_type.value());
        }
        if (archetype.confidence.has_value()) {
            cells.push_back(archetype.confidence.value());
        }
        if (archetype.reasoning.has_value()) {
            cells.push_back(archetype.reasoning.value());
        }
        if (archetype.color.has_value()) {
            cells.push_back(archetype.color.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
