// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/chronicle_event.fbs".

#include "chronicle_event.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    ChronicleEvent ChronicleEvent::clear_fields() {
        auto archetype = ChronicleEvent();
        archetype.source =
            ComponentBatch::empty<rerun::components::ChronicleSource>(Descriptor_source)
                .value_or_throw();
        archetype.event_type =
            ComponentBatch::empty<rerun::components::ChronicleEventType>(Descriptor_event_type)
                .value_or_throw();
        archetype.topic = ComponentBatch::empty<rerun::components::ChronicleTopic>(Descriptor_topic)
                              .value_or_throw();
        archetype.payload =
            ComponentBatch::empty<rerun::components::ChroniclePayload>(Descriptor_payload)
                .value_or_throw();
        archetype.color =
            ComponentBatch::empty<rerun::components::Color>(Descriptor_color).value_or_throw();
        archetype.label =
            ComponentBatch::empty<rerun::components::Text>(Descriptor_label).value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> ChronicleEvent::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(6);
        if (source.has_value()) {
            columns.push_back(source.value().partitioned(lengths_).value_or_throw());
        }
        if (event_type.has_value()) {
            columns.push_back(event_type.value().partitioned(lengths_).value_or_throw());
        }
        if (topic.has_value()) {
            columns.push_back(topic.value().partitioned(lengths_).value_or_throw());
        }
        if (payload.has_value()) {
            columns.push_back(payload.value().partitioned(lengths_).value_or_throw());
        }
        if (color.has_value()) {
            columns.push_back(color.value().partitioned(lengths_).value_or_throw());
        }
        if (label.has_value()) {
            columns.push_back(label.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> ChronicleEvent::columns() {
        if (source.has_value()) {
            return columns(std::vector<uint32_t>(source.value().length(), 1));
        }
        if (event_type.has_value()) {
            return columns(std::vector<uint32_t>(event_type.value().length(), 1));
        }
        if (topic.has_value()) {
            return columns(std::vector<uint32_t>(topic.value().length(), 1));
        }
        if (payload.has_value()) {
            return columns(std::vector<uint32_t>(payload.value().length(), 1));
        }
        if (color.has_value()) {
            return columns(std::vector<uint32_t>(color.value().length(), 1));
        }
        if (label.has_value()) {
            return columns(std::vector<uint32_t>(label.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::ChronicleEvent>::as_batches(
        const archetypes::ChronicleEvent& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(6);

        if (archetype.source.has_value()) {
            cells.push_back(archetype.source.value());
        }
        if (archetype.event_type.has_value()) {
            cells.push_back(archetype.event_type.value());
        }
        if (archetype.topic.has_value()) {
            cells.push_back(archetype.topic.value());
        }
        if (archetype.payload.has_value()) {
            cells.push_back(archetype.payload.value());
        }
        if (archetype.color.has_value()) {
            cells.push_back(archetype.color.value());
        }
        if (archetype.label.has_value()) {
            cells.push_back(archetype.label.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
