# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/chronicle_target_event.fbs".

# You can extend this class by creating a "ChronicleTargetEventExt" class in "chronicle_target_event_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["ChronicleTargetEvent", "ChronicleTargetEventBatch"]


class ChronicleTargetEvent(datatypes.Utf8, ComponentMixin):
    """**Component**: Entity path of the target event in a Chronicle link."""

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of ChronicleTargetEventExt in chronicle_target_event_ext.py

    # Note: there are no fields here because ChronicleTargetEvent delegates to datatypes.Utf8


class ChronicleTargetEventBatch(datatypes.Utf8Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.ChronicleTargetEvent"


# This is patched in late to avoid circular dependencies.
ChronicleTargetEvent._BATCH_TYPE = ChronicleTargetEventBatch  # type: ignore[assignment]
