# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/chronicle_source_event.fbs".

# You can extend this class by creating a "ChronicleSourceEventExt" class in "chronicle_source_event_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["ChronicleSourceEvent", "ChronicleSourceEventBatch"]


class ChronicleSourceEvent(datatypes.Utf8, ComponentMixin):
    """**Component**: Entity path of the source event in a Chronicle link."""

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of ChronicleSourceEventExt in chronicle_source_event_ext.py

    # Note: there are no fields here because ChronicleSourceEvent delegates to datatypes.Utf8


class ChronicleSourceEventBatch(datatypes.Utf8Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.ChronicleSourceEvent"


# This is patched in late to avoid circular dependencies.
ChronicleSourceEvent._BATCH_TYPE = ChronicleSourceEventBatch  # type: ignore[assignment]
