# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/chronicle_topic.fbs".

# You can extend this class by creating a "ChronicleTopicExt" class in "chronicle_topic_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["ChronicleTopic", "ChronicleTopicBatch"]


class ChronicleTopic(datatypes.Utf8, ComponentMixin):
    """**Component**: The topic of a Chronicle event (e.g. "payments", "tickets", "usage")."""

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of ChronicleTopicExt in chronicle_topic_ext.py

    # Note: there are no fields here because ChronicleTopic delegates to datatypes.Utf8


class ChronicleTopicBatch(datatypes.Utf8Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.ChronicleTopic"


# This is patched in late to avoid circular dependencies.
ChronicleTopic._BATCH_TYPE = ChronicleTopicBatch  # type: ignore[assignment]
