# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/chronicle_event_type.fbs".

# You can extend this class by creating a "ChronicleEventTypeExt" class in "chronicle_event_type_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["ChronicleEventType", "ChronicleEventTypeBatch"]


class ChronicleEventType(datatypes.Utf8, ComponentMixin):
    """**Component**: The type of a Chronicle event (e.g. "payment_intent.succeeded", "ticket.created")."""

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of ChronicleEventTypeExt in chronicle_event_type_ext.py

    # Note: there are no fields here because ChronicleEventType delegates to datatypes.Utf8


class ChronicleEventTypeBatch(datatypes.Utf8Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.ChronicleEventType"


# This is patched in late to avoid circular dependencies.
ChronicleEventType._BATCH_TYPE = ChronicleEventTypeBatch  # type: ignore[assignment]
