# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/chronicle_payload.fbs".

# You can extend this class by creating a "ChroniclePayloadExt" class in "chronicle_payload_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["ChroniclePayload", "ChroniclePayloadBatch"]


class ChroniclePayload(datatypes.Utf8, ComponentMixin):
    """**Component**: The JSON payload of a Chronicle event, serialized as a UTF-8 string."""

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of ChroniclePayloadExt in chronicle_payload_ext.py

    # Note: there are no fields here because ChroniclePayload delegates to datatypes.Utf8


class ChroniclePayloadBatch(datatypes.Utf8Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.ChroniclePayload"


# This is patched in late to avoid circular dependencies.
ChroniclePayload._BATCH_TYPE = ChroniclePayloadBatch  # type: ignore[assignment]
