# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/chronicle_entity_id.fbs".

# You can extend this class by creating a "ChronicleEntityIdExt" class in "chronicle_entity_id_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["ChronicleEntityId", "ChronicleEntityIdBatch"]


class ChronicleEntityId(datatypes.Utf8, ComponentMixin):
    """**Component**: The ID of a Chronicle entity (e.g. "cust_123", "tkt_456", "sess_789")."""

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of ChronicleEntityIdExt in chronicle_entity_id_ext.py

    # Note: there are no fields here because ChronicleEntityId delegates to datatypes.Utf8


class ChronicleEntityIdBatch(datatypes.Utf8Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.ChronicleEntityId"


# This is patched in late to avoid circular dependencies.
ChronicleEntityId._BATCH_TYPE = ChronicleEntityIdBatch  # type: ignore[assignment]
