# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/chronicle_confidence.fbs".

# You can extend this class by creating a "ChronicleConfidenceExt" class in "chronicle_confidence_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["ChronicleConfidence", "ChronicleConfidenceBatch"]


class ChronicleConfidence(datatypes.Float32, ComponentMixin):
    """
    **Component**: Confidence score (0.0 to 1.0) for a Chronicle event link.

    Controls visual opacity of link arcs in the ChronicleTimelineView.
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of ChronicleConfidenceExt in chronicle_confidence_ext.py

    # Note: there are no fields here because ChronicleConfidence delegates to datatypes.Float32


class ChronicleConfidenceBatch(datatypes.Float32Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.ChronicleConfidence"


# This is patched in late to avoid circular dependencies.
ChronicleConfidence._BATCH_TYPE = ChronicleConfidenceBatch  # type: ignore[assignment]
