# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/chronicle_source.fbs".

# You can extend this class by creating a "ChronicleSourceExt" class in "chronicle_source_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["ChronicleSource", "ChronicleSourceBatch"]


class ChronicleSource(datatypes.Utf8, ComponentMixin):
    """**Component**: The data source of a Chronicle event (e.g. "stripe", "support", "product")."""

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of ChronicleSourceExt in chronicle_source_ext.py

    # Note: there are no fields here because ChronicleSource delegates to datatypes.Utf8


class ChronicleSourceBatch(datatypes.Utf8Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.ChronicleSource"


# This is patched in late to avoid circular dependencies.
ChronicleSource._BATCH_TYPE = ChronicleSourceBatch  # type: ignore[assignment]
