# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/chronicle_reasoning.fbs".

# You can extend this class by creating a "ChronicleReasoningExt" class in "chronicle_reasoning_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["ChronicleReasoning", "ChronicleReasoningBatch"]


class ChronicleReasoning(datatypes.Utf8, ComponentMixin):
    """**Component**: Human-readable reasoning for why a Chronicle link was created."""

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of ChronicleReasoningExt in chronicle_reasoning_ext.py

    # Note: there are no fields here because ChronicleReasoning delegates to datatypes.Utf8


class ChronicleReasoningBatch(datatypes.Utf8Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.ChronicleReasoning"


# This is patched in late to avoid circular dependencies.
ChronicleReasoning._BATCH_TYPE = ChronicleReasoningBatch  # type: ignore[assignment]
