# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/chronicle_link_type.fbs".

# You can extend this class by creating a "ChronicleLinkTypeExt" class in "chronicle_link_type_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["ChronicleLinkType", "ChronicleLinkTypeBatch"]


class ChronicleLinkType(datatypes.Utf8, ComponentMixin):
    """**Component**: The type of a causal link between Chronicle events (e.g. "caused_by", "led_to", "triggered")."""

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of ChronicleLinkTypeExt in chronicle_link_type_ext.py

    # Note: there are no fields here because ChronicleLinkType delegates to datatypes.Utf8


class ChronicleLinkTypeBatch(datatypes.Utf8Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.ChronicleLinkType"


# This is patched in late to avoid circular dependencies.
ChronicleLinkType._BATCH_TYPE = ChronicleLinkTypeBatch  # type: ignore[assignment]
