# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/chronicle_entity_type.fbs".

# You can extend this class by creating a "ChronicleEntityTypeExt" class in "chronicle_entity_type_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["ChronicleEntityType", "ChronicleEntityTypeBatch"]


class ChronicleEntityType(datatypes.Utf8, ComponentMixin):
    """**Component**: The type of a Chronicle entity reference (e.g. "customer", "account", "session", "ticket")."""

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of ChronicleEntityTypeExt in chronicle_entity_type_ext.py

    # Note: there are no fields here because ChronicleEntityType delegates to datatypes.Utf8


class ChronicleEntityTypeBatch(datatypes.Utf8Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.ChronicleEntityType"


# This is patched in late to avoid circular dependencies.
ChronicleEntityType._BATCH_TYPE = ChronicleEntityTypeBatch  # type: ignore[assignment]
