# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/chronicle_entity_ref.fbs".

# You can extend this class by creating a "ChronicleEntityRefExt" class in "chronicle_entity_ref_ext.py".

from __future__ import annotations

from typing import TYPE_CHECKING, Any

import numpy as np
import pyarrow as pa
from attrs import define, field

from .. import components, datatypes
from .._baseclasses import (
    Archetype,
    ComponentColumnList,
)
from ..blueprint import VisualizableArchetype, Visualizer
from ..error_utils import catch_and_log_exceptions

if TYPE_CHECKING:
    from ..blueprint.datatypes import VisualizerComponentMappingLike

__all__ = ["ChronicleEntityRef"]


@define(str=False, repr=False, init=False)
class ChronicleEntityRef(Archetype, VisualizableArchetype):
    """
    **Archetype**: An entity reference associating a Chronicle event with a typed entity.

    Entity refs are the many-to-many mapping between events and entities
    (e.g. linking an event to customer "cust_123" and ticket "tkt_456").
    Logged as a component on the event entity path.
    """

    def __init__(self: Any, entity_type: datatypes.Utf8Like, entity_id: datatypes.Utf8Like) -> None:
        """
        Create a new instance of the ChronicleEntityRef archetype.

        Parameters
        ----------
        entity_type:
            The type of the referenced entity (e.g. "customer", "account", "ticket").
        entity_id:
            The ID of the referenced entity (e.g. "cust_123", "tkt_456").

        """

        # You can define your own __init__ function as a member of ChronicleEntityRefExt in chronicle_entity_ref_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(entity_type=entity_type, entity_id=entity_id)
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            entity_type=None,
            entity_id=None,
        )

    @classmethod
    def _clear(cls) -> ChronicleEntityRef:
        """Produce an empty ChronicleEntityRef, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        entity_type: datatypes.Utf8Like | None = None,
        entity_id: datatypes.Utf8Like | None = None,
    ) -> ChronicleEntityRef:
        """
        Update only some specific fields of a `ChronicleEntityRef`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        entity_type:
            The type of the referenced entity (e.g. "customer", "account", "ticket").
        entity_id:
            The ID of the referenced entity (e.g. "cust_123", "tkt_456").

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "entity_type": entity_type,
                "entity_id": entity_id,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> ChronicleEntityRef:
        """Clear all the fields of a `ChronicleEntityRef`."""
        return cls.from_fields(clear_unset=True)

    @classmethod
    def columns(
        cls,
        *,
        entity_type: datatypes.Utf8ArrayLike | None = None,
        entity_id: datatypes.Utf8ArrayLike | None = None,
    ) -> ComponentColumnList:
        """
        Construct a new column-oriented component bundle.

        This makes it possible to use `rr.send_columns` to send columnar data directly into Rerun.

        The returned columns will be partitioned into unit-length sub-batches by default.
        Use `ComponentColumnList.partition` to repartition the data as needed.

        Parameters
        ----------
        entity_type:
            The type of the referenced entity (e.g. "customer", "account", "ticket").
        entity_id:
            The ID of the referenced entity (e.g. "cust_123", "tkt_456").

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            inst.__attrs_init__(
                entity_type=entity_type,
                entity_id=entity_id,
            )

        batches = inst.as_component_batches()
        if len(batches) == 0:
            return ComponentColumnList([])

        kwargs = {"ChronicleEntityRef:entity_type": entity_type, "ChronicleEntityRef:entity_id": entity_id}
        columns = []

        for batch in batches:
            arrow_array = batch.as_arrow_array()

            # For primitive arrays and fixed size list arrays, we infer partition size from the input shape.
            if pa.types.is_primitive(arrow_array.type) or pa.types.is_fixed_size_list(arrow_array.type):
                param = kwargs[batch.component_descriptor().component]  # type: ignore[index]
                shape = np.shape(param)  # type: ignore[arg-type]
                elem_flat_len = int(np.prod(shape[1:])) if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]

                if pa.types.is_fixed_size_list(arrow_array.type) and arrow_array.type.list_size == elem_flat_len:
                    # If the product of the last dimensions of the shape are equal to the size of the fixed size list array,
                    # we have `num_rows` single element batches (each element is a fixed sized list).
                    # (This should have been already validated by conversion to the arrow_array)
                    batch_length = 1
                else:
                    batch_length = shape[1] if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]

                num_rows = shape[0] if len(shape) >= 1 else 1  # type: ignore[redundant-expr,misc]
                sizes = batch_length * np.ones(num_rows)
            else:
                # For non-primitive types, default to partitioning each element separately.
                sizes = np.ones(len(arrow_array))

            columns.append(batch.partition(sizes))

        return ComponentColumnList(columns)

    entity_type: components.ChronicleEntityTypeBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ChronicleEntityTypeBatch._converter,  # type: ignore[misc]
    )
    # The type of the referenced entity (e.g. "customer", "account", "ticket").
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    entity_id: components.ChronicleEntityIdBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ChronicleEntityIdBatch._converter,  # type: ignore[misc]
    )
    # The ID of the referenced entity (e.g. "cust_123", "tkt_456").
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]

    def visualizer(self, *, mappings: list[VisualizerComponentMappingLike] | None = None) -> Visualizer:
        """
        Creates a visualizer for this archetype, using all currently set values as overrides.

        Parameters
        ----------
        mappings:
            Optional component mappings to control how the visualizer sources its data.

            ⚠️ **Experimental**: Component mappings are an experimental feature and may change.
            See https://github.com/rerun-io/rerun/issues/10631 for more information.

        """
        return Visualizer("ChronicleEntityRef", overrides=self.as_component_batches(), mappings=mappings)
