# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/chronicle_link.fbs".

# You can extend this class by creating a "ChronicleLinkExt" class in "chronicle_link_ext.py".

from __future__ import annotations

from typing import TYPE_CHECKING, Any

import numpy as np
import pyarrow as pa
from attrs import define, field

from .. import components, datatypes
from .._baseclasses import (
    Archetype,
    ComponentColumnList,
)
from ..blueprint import VisualizableArchetype, Visualizer
from ..error_utils import catch_and_log_exceptions

if TYPE_CHECKING:
    from ..blueprint.datatypes import VisualizerComponentMappingLike

__all__ = ["ChronicleLink"]


@define(str=False, repr=False, init=False)
class ChronicleLink(Archetype, VisualizableArchetype):
    """
    **Archetype**: A causal or relational link between two Chronicle events.

    Links represent directed edges in the event graph (e.g. "payment failure
    caused support ticket"). They are rendered as Bezier arcs in the
    ChronicleTimelineView.
    """

    def __init__(
        self: Any,
        *,
        source_event: datatypes.Utf8Like,
        target_event: datatypes.Utf8Like,
        link_type: datatypes.Utf8Like,
        confidence: datatypes.Float32Like | None = None,
        reasoning: datatypes.Utf8Like | None = None,
        color: datatypes.Rgba32Like | None = None,
    ) -> None:
        """
        Create a new instance of the ChronicleLink archetype.

        Parameters
        ----------
        source_event:
            Entity path of the source event.
        target_event:
            Entity path of the target event.
        link_type:
            Type of the link (e.g. "caused_by", "led_to", "triggered", "related_to").
        confidence:
            Confidence score (0.0 to 1.0). Controls arc opacity in the viewer.
        reasoning:
            Human-readable reasoning for why this link exists.
        color:
            Optional color override for the link arc.

        """

        # You can define your own __init__ function as a member of ChronicleLinkExt in chronicle_link_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(
                source_event=source_event,
                target_event=target_event,
                link_type=link_type,
                confidence=confidence,
                reasoning=reasoning,
                color=color,
            )
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            source_event=None,
            target_event=None,
            link_type=None,
            confidence=None,
            reasoning=None,
            color=None,
        )

    @classmethod
    def _clear(cls) -> ChronicleLink:
        """Produce an empty ChronicleLink, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        source_event: datatypes.Utf8Like | None = None,
        target_event: datatypes.Utf8Like | None = None,
        link_type: datatypes.Utf8Like | None = None,
        confidence: datatypes.Float32Like | None = None,
        reasoning: datatypes.Utf8Like | None = None,
        color: datatypes.Rgba32Like | None = None,
    ) -> ChronicleLink:
        """
        Update only some specific fields of a `ChronicleLink`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        source_event:
            Entity path of the source event.
        target_event:
            Entity path of the target event.
        link_type:
            Type of the link (e.g. "caused_by", "led_to", "triggered", "related_to").
        confidence:
            Confidence score (0.0 to 1.0). Controls arc opacity in the viewer.
        reasoning:
            Human-readable reasoning for why this link exists.
        color:
            Optional color override for the link arc.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "source_event": source_event,
                "target_event": target_event,
                "link_type": link_type,
                "confidence": confidence,
                "reasoning": reasoning,
                "color": color,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> ChronicleLink:
        """Clear all the fields of a `ChronicleLink`."""
        return cls.from_fields(clear_unset=True)

    @classmethod
    def columns(
        cls,
        *,
        source_event: datatypes.Utf8ArrayLike | None = None,
        target_event: datatypes.Utf8ArrayLike | None = None,
        link_type: datatypes.Utf8ArrayLike | None = None,
        confidence: datatypes.Float32ArrayLike | None = None,
        reasoning: datatypes.Utf8ArrayLike | None = None,
        color: datatypes.Rgba32ArrayLike | None = None,
    ) -> ComponentColumnList:
        """
        Construct a new column-oriented component bundle.

        This makes it possible to use `rr.send_columns` to send columnar data directly into Rerun.

        The returned columns will be partitioned into unit-length sub-batches by default.
        Use `ComponentColumnList.partition` to repartition the data as needed.

        Parameters
        ----------
        source_event:
            Entity path of the source event.
        target_event:
            Entity path of the target event.
        link_type:
            Type of the link (e.g. "caused_by", "led_to", "triggered", "related_to").
        confidence:
            Confidence score (0.0 to 1.0). Controls arc opacity in the viewer.
        reasoning:
            Human-readable reasoning for why this link exists.
        color:
            Optional color override for the link arc.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            inst.__attrs_init__(
                source_event=source_event,
                target_event=target_event,
                link_type=link_type,
                confidence=confidence,
                reasoning=reasoning,
                color=color,
            )

        batches = inst.as_component_batches()
        if len(batches) == 0:
            return ComponentColumnList([])

        kwargs = {
            "ChronicleLink:source_event": source_event,
            "ChronicleLink:target_event": target_event,
            "ChronicleLink:link_type": link_type,
            "ChronicleLink:confidence": confidence,
            "ChronicleLink:reasoning": reasoning,
            "ChronicleLink:color": color,
        }
        columns = []

        for batch in batches:
            arrow_array = batch.as_arrow_array()

            # For primitive arrays and fixed size list arrays, we infer partition size from the input shape.
            if pa.types.is_primitive(arrow_array.type) or pa.types.is_fixed_size_list(arrow_array.type):
                param = kwargs[batch.component_descriptor().component]  # type: ignore[index]
                shape = np.shape(param)  # type: ignore[arg-type]
                elem_flat_len = int(np.prod(shape[1:])) if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]

                if pa.types.is_fixed_size_list(arrow_array.type) and arrow_array.type.list_size == elem_flat_len:
                    # If the product of the last dimensions of the shape are equal to the size of the fixed size list array,
                    # we have `num_rows` single element batches (each element is a fixed sized list).
                    # (This should have been already validated by conversion to the arrow_array)
                    batch_length = 1
                else:
                    batch_length = shape[1] if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]

                num_rows = shape[0] if len(shape) >= 1 else 1  # type: ignore[redundant-expr,misc]
                sizes = batch_length * np.ones(num_rows)
            else:
                # For non-primitive types, default to partitioning each element separately.
                sizes = np.ones(len(arrow_array))

            columns.append(batch.partition(sizes))

        return ComponentColumnList(columns)

    source_event: components.ChronicleSourceEventBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ChronicleSourceEventBatch._converter,  # type: ignore[misc]
    )
    # Entity path of the source event.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    target_event: components.ChronicleTargetEventBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ChronicleTargetEventBatch._converter,  # type: ignore[misc]
    )
    # Entity path of the target event.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    link_type: components.ChronicleLinkTypeBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ChronicleLinkTypeBatch._converter,  # type: ignore[misc]
    )
    # Type of the link (e.g. "caused_by", "led_to", "triggered", "related_to").
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    confidence: components.ChronicleConfidenceBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ChronicleConfidenceBatch._converter,  # type: ignore[misc]
    )
    # Confidence score (0.0 to 1.0). Controls arc opacity in the viewer.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    reasoning: components.ChronicleReasoningBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ChronicleReasoningBatch._converter,  # type: ignore[misc]
    )
    # Human-readable reasoning for why this link exists.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    color: components.ColorBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ColorBatch._converter,  # type: ignore[misc]
    )
    # Optional color override for the link arc.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]

    def visualizer(self, *, mappings: list[VisualizerComponentMappingLike] | None = None) -> Visualizer:
        """
        Creates a visualizer for this archetype, using all currently set values as overrides.

        Parameters
        ----------
        mappings:
            Optional component mappings to control how the visualizer sources its data.

            ⚠️ **Experimental**: Component mappings are an experimental feature and may change.
            See https://github.com/rerun-io/rerun/issues/10631 for more information.

        """
        return Visualizer("ChronicleLink", overrides=self.as_component_batches(), mappings=mappings)
