# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/chronicle_event.fbs".

# You can extend this class by creating a "ChronicleEventExt" class in "chronicle_event_ext.py".

from __future__ import annotations

from typing import TYPE_CHECKING, Any

import numpy as np
import pyarrow as pa
from attrs import define, field

from .. import components, datatypes
from .._baseclasses import (
    Archetype,
    ComponentColumnList,
)
from ..blueprint import VisualizableArchetype, Visualizer
from ..error_utils import catch_and_log_exceptions

if TYPE_CHECKING:
    from ..blueprint.datatypes import VisualizerComponentMappingLike

__all__ = ["ChronicleEvent"]


@define(str=False, repr=False, init=False)
class ChronicleEvent(Archetype, VisualizableArchetype):
    """
    **Archetype**: A Chronicle SaaS event with source, type, and optional JSON payload.

    Events are the core data type in Chronicle. Each event represents a
    single occurrence from a SaaS source (e.g. a Stripe payment, a support
    ticket, a product page view). Events are logged at entity paths that
    encode the entity hierarchy: `/{org}/{entity_type}/{entity_id}/{source}/{event_type}`.
    """

    def __init__(
        self: Any,
        source: datatypes.Utf8Like,
        event_type: datatypes.Utf8Like,
        *,
        topic: datatypes.Utf8Like | None = None,
        payload: datatypes.Utf8Like | None = None,
        color: datatypes.Rgba32Like | None = None,
        label: datatypes.Utf8Like | None = None,
    ) -> None:
        """
        Create a new instance of the ChronicleEvent archetype.

        Parameters
        ----------
        source:
            The data source (e.g. "stripe", "support", "product", "marketing").
        event_type:
            The event type (e.g. "payment_intent.succeeded", "ticket.created").
        topic:
            The topic/category (e.g. "payments", "tickets", "usage").
        payload:
            JSON payload serialized as a string.
        color:
            Optional color for the event marker.
        label:
            Optional text label.

        """

        # You can define your own __init__ function as a member of ChronicleEventExt in chronicle_event_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(
                source=source, event_type=event_type, topic=topic, payload=payload, color=color, label=label
            )
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            source=None,
            event_type=None,
            topic=None,
            payload=None,
            color=None,
            label=None,
        )

    @classmethod
    def _clear(cls) -> ChronicleEvent:
        """Produce an empty ChronicleEvent, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        source: datatypes.Utf8Like | None = None,
        event_type: datatypes.Utf8Like | None = None,
        topic: datatypes.Utf8Like | None = None,
        payload: datatypes.Utf8Like | None = None,
        color: datatypes.Rgba32Like | None = None,
        label: datatypes.Utf8Like | None = None,
    ) -> ChronicleEvent:
        """
        Update only some specific fields of a `ChronicleEvent`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        source:
            The data source (e.g. "stripe", "support", "product", "marketing").
        event_type:
            The event type (e.g. "payment_intent.succeeded", "ticket.created").
        topic:
            The topic/category (e.g. "payments", "tickets", "usage").
        payload:
            JSON payload serialized as a string.
        color:
            Optional color for the event marker.
        label:
            Optional text label.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "source": source,
                "event_type": event_type,
                "topic": topic,
                "payload": payload,
                "color": color,
                "label": label,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> ChronicleEvent:
        """Clear all the fields of a `ChronicleEvent`."""
        return cls.from_fields(clear_unset=True)

    @classmethod
    def columns(
        cls,
        *,
        source: datatypes.Utf8ArrayLike | None = None,
        event_type: datatypes.Utf8ArrayLike | None = None,
        topic: datatypes.Utf8ArrayLike | None = None,
        payload: datatypes.Utf8ArrayLike | None = None,
        color: datatypes.Rgba32ArrayLike | None = None,
        label: datatypes.Utf8ArrayLike | None = None,
    ) -> ComponentColumnList:
        """
        Construct a new column-oriented component bundle.

        This makes it possible to use `rr.send_columns` to send columnar data directly into Rerun.

        The returned columns will be partitioned into unit-length sub-batches by default.
        Use `ComponentColumnList.partition` to repartition the data as needed.

        Parameters
        ----------
        source:
            The data source (e.g. "stripe", "support", "product", "marketing").
        event_type:
            The event type (e.g. "payment_intent.succeeded", "ticket.created").
        topic:
            The topic/category (e.g. "payments", "tickets", "usage").
        payload:
            JSON payload serialized as a string.
        color:
            Optional color for the event marker.
        label:
            Optional text label.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            inst.__attrs_init__(
                source=source,
                event_type=event_type,
                topic=topic,
                payload=payload,
                color=color,
                label=label,
            )

        batches = inst.as_component_batches()
        if len(batches) == 0:
            return ComponentColumnList([])

        kwargs = {
            "ChronicleEvent:source": source,
            "ChronicleEvent:event_type": event_type,
            "ChronicleEvent:topic": topic,
            "ChronicleEvent:payload": payload,
            "ChronicleEvent:color": color,
            "ChronicleEvent:label": label,
        }
        columns = []

        for batch in batches:
            arrow_array = batch.as_arrow_array()

            # For primitive arrays and fixed size list arrays, we infer partition size from the input shape.
            if pa.types.is_primitive(arrow_array.type) or pa.types.is_fixed_size_list(arrow_array.type):
                param = kwargs[batch.component_descriptor().component]  # type: ignore[index]
                shape = np.shape(param)  # type: ignore[arg-type]
                elem_flat_len = int(np.prod(shape[1:])) if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]

                if pa.types.is_fixed_size_list(arrow_array.type) and arrow_array.type.list_size == elem_flat_len:
                    # If the product of the last dimensions of the shape are equal to the size of the fixed size list array,
                    # we have `num_rows` single element batches (each element is a fixed sized list).
                    # (This should have been already validated by conversion to the arrow_array)
                    batch_length = 1
                else:
                    batch_length = shape[1] if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]

                num_rows = shape[0] if len(shape) >= 1 else 1  # type: ignore[redundant-expr,misc]
                sizes = batch_length * np.ones(num_rows)
            else:
                # For non-primitive types, default to partitioning each element separately.
                sizes = np.ones(len(arrow_array))

            columns.append(batch.partition(sizes))

        return ComponentColumnList(columns)

    source: components.ChronicleSourceBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ChronicleSourceBatch._converter,  # type: ignore[misc]
    )
    # The data source (e.g. "stripe", "support", "product", "marketing").
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    event_type: components.ChronicleEventTypeBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ChronicleEventTypeBatch._converter,  # type: ignore[misc]
    )
    # The event type (e.g. "payment_intent.succeeded", "ticket.created").
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    topic: components.ChronicleTopicBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ChronicleTopicBatch._converter,  # type: ignore[misc]
    )
    # The topic/category (e.g. "payments", "tickets", "usage").
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    payload: components.ChroniclePayloadBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ChroniclePayloadBatch._converter,  # type: ignore[misc]
    )
    # JSON payload serialized as a string.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    color: components.ColorBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ColorBatch._converter,  # type: ignore[misc]
    )
    # Optional color for the event marker.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    label: components.TextBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.TextBatch._converter,  # type: ignore[misc]
    )
    # Optional text label.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]

    def visualizer(self, *, mappings: list[VisualizerComponentMappingLike] | None = None) -> Visualizer:
        """
        Creates a visualizer for this archetype, using all currently set values as overrides.

        Parameters
        ----------
        mappings:
            Optional component mappings to control how the visualizer sources its data.

            ⚠️ **Experimental**: Component mappings are an experimental feature and may change.
            See https://github.com/rerun-io/rerun/issues/10631 for more information.

        """
        return Visualizer("ChronicleEvent", overrides=self.as_component_batches(), mappings=mappings)
