// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/chronicle_link.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: A causal or relational link between two Chronicle events.
///
/// Links represent directed edges in the event graph (e.g. "payment failure
/// caused support ticket"). They are rendered as Bezier arcs in the
/// ChronicleTimelineView.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct ChronicleLink {
    /// Entity path of the source event.
    pub source_event: Option<SerializedComponentBatch>,

    /// Entity path of the target event.
    pub target_event: Option<SerializedComponentBatch>,

    /// Type of the link (e.g. "caused_by", "led_to", "triggered", "related_to").
    pub link_type: Option<SerializedComponentBatch>,

    /// Confidence score (0.0 to 1.0). Controls arc opacity in the viewer.
    pub confidence: Option<SerializedComponentBatch>,

    /// Human-readable reasoning for why this link exists.
    pub reasoning: Option<SerializedComponentBatch>,

    /// Optional color override for the link arc.
    pub color: Option<SerializedComponentBatch>,
}

impl ChronicleLink {
    /// Returns the [`ComponentDescriptor`] for [`Self::source_event`].
    ///
    /// The corresponding component is [`crate::components::ChronicleSourceEvent`].
    #[inline]
    pub fn descriptor_source_event() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.ChronicleLink".into()),
            component: "ChronicleLink:source_event".into(),
            component_type: Some("rerun.components.ChronicleSourceEvent".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::target_event`].
    ///
    /// The corresponding component is [`crate::components::ChronicleTargetEvent`].
    #[inline]
    pub fn descriptor_target_event() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.ChronicleLink".into()),
            component: "ChronicleLink:target_event".into(),
            component_type: Some("rerun.components.ChronicleTargetEvent".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::link_type`].
    ///
    /// The corresponding component is [`crate::components::ChronicleLinkType`].
    #[inline]
    pub fn descriptor_link_type() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.ChronicleLink".into()),
            component: "ChronicleLink:link_type".into(),
            component_type: Some("rerun.components.ChronicleLinkType".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::confidence`].
    ///
    /// The corresponding component is [`crate::components::ChronicleConfidence`].
    #[inline]
    pub fn descriptor_confidence() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.ChronicleLink".into()),
            component: "ChronicleLink:confidence".into(),
            component_type: Some("rerun.components.ChronicleConfidence".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::reasoning`].
    ///
    /// The corresponding component is [`crate::components::ChronicleReasoning`].
    #[inline]
    pub fn descriptor_reasoning() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.ChronicleLink".into()),
            component: "ChronicleLink:reasoning".into(),
            component_type: Some("rerun.components.ChronicleReasoning".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::color`].
    ///
    /// The corresponding component is [`crate::components::Color`].
    #[inline]
    pub fn descriptor_color() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.ChronicleLink".into()),
            component: "ChronicleLink:color".into(),
            component_type: Some("rerun.components.Color".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 3usize]> =
    std::sync::LazyLock::new(|| {
        [
            ChronicleLink::descriptor_source_event(),
            ChronicleLink::descriptor_target_event(),
            ChronicleLink::descriptor_link_type(),
        ]
    });

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [ChronicleLink::descriptor_confidence()]);

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| {
        [
            ChronicleLink::descriptor_reasoning(),
            ChronicleLink::descriptor_color(),
        ]
    });

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 6usize]> =
    std::sync::LazyLock::new(|| {
        [
            ChronicleLink::descriptor_source_event(),
            ChronicleLink::descriptor_target_event(),
            ChronicleLink::descriptor_link_type(),
            ChronicleLink::descriptor_confidence(),
            ChronicleLink::descriptor_reasoning(),
            ChronicleLink::descriptor_color(),
        ]
    });

impl ChronicleLink {
    /// The total number of components in the archetype: 3 required, 1 recommended, 2 optional
    pub const NUM_COMPONENTS: usize = 6usize;
}

impl ::re_types_core::Archetype for ChronicleLink {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.archetypes.ChronicleLink".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Chronicle link"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let source_event = arrays_by_descr
            .get(&Self::descriptor_source_event())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_source_event())
            });
        let target_event = arrays_by_descr
            .get(&Self::descriptor_target_event())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_target_event())
            });
        let link_type = arrays_by_descr
            .get(&Self::descriptor_link_type())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_link_type())
            });
        let confidence = arrays_by_descr
            .get(&Self::descriptor_confidence())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_confidence())
            });
        let reasoning = arrays_by_descr
            .get(&Self::descriptor_reasoning())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_reasoning())
            });
        let color = arrays_by_descr
            .get(&Self::descriptor_color())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_color()));
        Ok(Self {
            source_event,
            target_event,
            link_type,
            confidence,
            reasoning,
            color,
        })
    }
}

impl ::re_types_core::AsComponents for ChronicleLink {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            self.source_event.clone(),
            self.target_event.clone(),
            self.link_type.clone(),
            self.confidence.clone(),
            self.reasoning.clone(),
            self.color.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for ChronicleLink {}

impl crate::VisualizableArchetype for ChronicleLink {
    #[inline]
    fn visualizer(&self) -> crate::Visualizer {
        crate::Visualizer::new("ChronicleLink").with_overrides(self)
    }
}

impl ChronicleLink {
    /// Create a new `ChronicleLink`.
    #[inline]
    pub fn new(
        source_event: impl Into<crate::components::ChronicleSourceEvent>,
        target_event: impl Into<crate::components::ChronicleTargetEvent>,
        link_type: impl Into<crate::components::ChronicleLinkType>,
    ) -> Self {
        Self {
            source_event: try_serialize_field(Self::descriptor_source_event(), [source_event]),
            target_event: try_serialize_field(Self::descriptor_target_event(), [target_event]),
            link_type: try_serialize_field(Self::descriptor_link_type(), [link_type]),
            confidence: None,
            reasoning: None,
            color: None,
        }
    }

    /// Update only some specific fields of a `ChronicleLink`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `ChronicleLink`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            source_event: Some(SerializedComponentBatch::new(
                crate::components::ChronicleSourceEvent::arrow_empty(),
                Self::descriptor_source_event(),
            )),
            target_event: Some(SerializedComponentBatch::new(
                crate::components::ChronicleTargetEvent::arrow_empty(),
                Self::descriptor_target_event(),
            )),
            link_type: Some(SerializedComponentBatch::new(
                crate::components::ChronicleLinkType::arrow_empty(),
                Self::descriptor_link_type(),
            )),
            confidence: Some(SerializedComponentBatch::new(
                crate::components::ChronicleConfidence::arrow_empty(),
                Self::descriptor_confidence(),
            )),
            reasoning: Some(SerializedComponentBatch::new(
                crate::components::ChronicleReasoning::arrow_empty(),
                Self::descriptor_reasoning(),
            )),
            color: Some(SerializedComponentBatch::new(
                crate::components::Color::arrow_empty(),
                Self::descriptor_color(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.source_event
                .map(|source_event| source_event.partitioned(_lengths.clone()))
                .transpose()?,
            self.target_event
                .map(|target_event| target_event.partitioned(_lengths.clone()))
                .transpose()?,
            self.link_type
                .map(|link_type| link_type.partitioned(_lengths.clone()))
                .transpose()?,
            self.confidence
                .map(|confidence| confidence.partitioned(_lengths.clone()))
                .transpose()?,
            self.reasoning
                .map(|reasoning| reasoning.partitioned(_lengths.clone()))
                .transpose()?,
            self.color
                .map(|color| color.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_source_event = self.source_event.as_ref().map(|b| b.array.len());
        let len_target_event = self.target_event.as_ref().map(|b| b.array.len());
        let len_link_type = self.link_type.as_ref().map(|b| b.array.len());
        let len_confidence = self.confidence.as_ref().map(|b| b.array.len());
        let len_reasoning = self.reasoning.as_ref().map(|b| b.array.len());
        let len_color = self.color.as_ref().map(|b| b.array.len());
        let len = None
            .or(len_source_event)
            .or(len_target_event)
            .or(len_link_type)
            .or(len_confidence)
            .or(len_reasoning)
            .or(len_color)
            .unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// Entity path of the source event.
    #[inline]
    pub fn with_source_event(
        mut self,
        source_event: impl Into<crate::components::ChronicleSourceEvent>,
    ) -> Self {
        self.source_event = try_serialize_field(Self::descriptor_source_event(), [source_event]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::ChronicleSourceEvent`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_source_event`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_source_event(
        mut self,
        source_event: impl IntoIterator<Item = impl Into<crate::components::ChronicleSourceEvent>>,
    ) -> Self {
        self.source_event = try_serialize_field(Self::descriptor_source_event(), source_event);
        self
    }

    /// Entity path of the target event.
    #[inline]
    pub fn with_target_event(
        mut self,
        target_event: impl Into<crate::components::ChronicleTargetEvent>,
    ) -> Self {
        self.target_event = try_serialize_field(Self::descriptor_target_event(), [target_event]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::ChronicleTargetEvent`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_target_event`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_target_event(
        mut self,
        target_event: impl IntoIterator<Item = impl Into<crate::components::ChronicleTargetEvent>>,
    ) -> Self {
        self.target_event = try_serialize_field(Self::descriptor_target_event(), target_event);
        self
    }

    /// Type of the link (e.g. "caused_by", "led_to", "triggered", "related_to").
    #[inline]
    pub fn with_link_type(
        mut self,
        link_type: impl Into<crate::components::ChronicleLinkType>,
    ) -> Self {
        self.link_type = try_serialize_field(Self::descriptor_link_type(), [link_type]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::ChronicleLinkType`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_link_type`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_link_type(
        mut self,
        link_type: impl IntoIterator<Item = impl Into<crate::components::ChronicleLinkType>>,
    ) -> Self {
        self.link_type = try_serialize_field(Self::descriptor_link_type(), link_type);
        self
    }

    /// Confidence score (0.0 to 1.0). Controls arc opacity in the viewer.
    #[inline]
    pub fn with_confidence(
        mut self,
        confidence: impl Into<crate::components::ChronicleConfidence>,
    ) -> Self {
        self.confidence = try_serialize_field(Self::descriptor_confidence(), [confidence]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::ChronicleConfidence`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_confidence`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_confidence(
        mut self,
        confidence: impl IntoIterator<Item = impl Into<crate::components::ChronicleConfidence>>,
    ) -> Self {
        self.confidence = try_serialize_field(Self::descriptor_confidence(), confidence);
        self
    }

    /// Human-readable reasoning for why this link exists.
    #[inline]
    pub fn with_reasoning(
        mut self,
        reasoning: impl Into<crate::components::ChronicleReasoning>,
    ) -> Self {
        self.reasoning = try_serialize_field(Self::descriptor_reasoning(), [reasoning]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::ChronicleReasoning`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_reasoning`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_reasoning(
        mut self,
        reasoning: impl IntoIterator<Item = impl Into<crate::components::ChronicleReasoning>>,
    ) -> Self {
        self.reasoning = try_serialize_field(Self::descriptor_reasoning(), reasoning);
        self
    }

    /// Optional color override for the link arc.
    #[inline]
    pub fn with_color(mut self, color: impl Into<crate::components::Color>) -> Self {
        self.color = try_serialize_field(Self::descriptor_color(), [color]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Color`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_color`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_color(
        mut self,
        color: impl IntoIterator<Item = impl Into<crate::components::Color>>,
    ) -> Self {
        self.color = try_serialize_field(Self::descriptor_color(), color);
        self
    }
}

impl ::re_byte_size::SizeBytes for ChronicleLink {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.source_event.heap_size_bytes()
            + self.target_event.heap_size_bytes()
            + self.link_type.heap_size_bytes()
            + self.confidence.heap_size_bytes()
            + self.reasoning.heap_size_bytes()
            + self.color.heap_size_bytes()
    }
}
