// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/chronicle_entity_ref.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: An entity reference associating a Chronicle event with a typed entity.
///
/// Entity refs are the many-to-many mapping between events and entities
/// (e.g. linking an event to customer "cust_123" and ticket "tkt_456").
/// Logged as a component on the event entity path.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct ChronicleEntityRef {
    /// The type of the referenced entity (e.g. "customer", "account", "ticket").
    pub entity_type: Option<SerializedComponentBatch>,

    /// The ID of the referenced entity (e.g. "cust_123", "tkt_456").
    pub entity_id: Option<SerializedComponentBatch>,
}

impl ChronicleEntityRef {
    /// Returns the [`ComponentDescriptor`] for [`Self::entity_type`].
    ///
    /// The corresponding component is [`crate::components::ChronicleEntityType`].
    #[inline]
    pub fn descriptor_entity_type() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.ChronicleEntityRef".into()),
            component: "ChronicleEntityRef:entity_type".into(),
            component_type: Some("rerun.components.ChronicleEntityType".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::entity_id`].
    ///
    /// The corresponding component is [`crate::components::ChronicleEntityId`].
    #[inline]
    pub fn descriptor_entity_id() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.ChronicleEntityRef".into()),
            component: "ChronicleEntityRef:entity_id".into(),
            component_type: Some("rerun.components.ChronicleEntityId".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| {
        [
            ChronicleEntityRef::descriptor_entity_type(),
            ChronicleEntityRef::descriptor_entity_id(),
        ]
    });

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| {
        [
            ChronicleEntityRef::descriptor_entity_type(),
            ChronicleEntityRef::descriptor_entity_id(),
        ]
    });

impl ChronicleEntityRef {
    /// The total number of components in the archetype: 2 required, 0 recommended, 0 optional
    pub const NUM_COMPONENTS: usize = 2usize;
}

impl ::re_types_core::Archetype for ChronicleEntityRef {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.archetypes.ChronicleEntityRef".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Chronicle entity ref"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let entity_type = arrays_by_descr
            .get(&Self::descriptor_entity_type())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_entity_type())
            });
        let entity_id = arrays_by_descr
            .get(&Self::descriptor_entity_id())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_entity_id())
            });
        Ok(Self {
            entity_type,
            entity_id,
        })
    }
}

impl ::re_types_core::AsComponents for ChronicleEntityRef {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [self.entity_type.clone(), self.entity_id.clone()]
            .into_iter()
            .flatten()
            .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for ChronicleEntityRef {}

impl crate::VisualizableArchetype for ChronicleEntityRef {
    #[inline]
    fn visualizer(&self) -> crate::Visualizer {
        crate::Visualizer::new("ChronicleEntityRef").with_overrides(self)
    }
}

impl ChronicleEntityRef {
    /// Create a new `ChronicleEntityRef`.
    #[inline]
    pub fn new(
        entity_type: impl Into<crate::components::ChronicleEntityType>,
        entity_id: impl Into<crate::components::ChronicleEntityId>,
    ) -> Self {
        Self {
            entity_type: try_serialize_field(Self::descriptor_entity_type(), [entity_type]),
            entity_id: try_serialize_field(Self::descriptor_entity_id(), [entity_id]),
        }
    }

    /// Update only some specific fields of a `ChronicleEntityRef`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `ChronicleEntityRef`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            entity_type: Some(SerializedComponentBatch::new(
                crate::components::ChronicleEntityType::arrow_empty(),
                Self::descriptor_entity_type(),
            )),
            entity_id: Some(SerializedComponentBatch::new(
                crate::components::ChronicleEntityId::arrow_empty(),
                Self::descriptor_entity_id(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.entity_type
                .map(|entity_type| entity_type.partitioned(_lengths.clone()))
                .transpose()?,
            self.entity_id
                .map(|entity_id| entity_id.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_entity_type = self.entity_type.as_ref().map(|b| b.array.len());
        let len_entity_id = self.entity_id.as_ref().map(|b| b.array.len());
        let len = None.or(len_entity_type).or(len_entity_id).unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// The type of the referenced entity (e.g. "customer", "account", "ticket").
    #[inline]
    pub fn with_entity_type(
        mut self,
        entity_type: impl Into<crate::components::ChronicleEntityType>,
    ) -> Self {
        self.entity_type = try_serialize_field(Self::descriptor_entity_type(), [entity_type]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::ChronicleEntityType`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_entity_type`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_entity_type(
        mut self,
        entity_type: impl IntoIterator<Item = impl Into<crate::components::ChronicleEntityType>>,
    ) -> Self {
        self.entity_type = try_serialize_field(Self::descriptor_entity_type(), entity_type);
        self
    }

    /// The ID of the referenced entity (e.g. "cust_123", "tkt_456").
    #[inline]
    pub fn with_entity_id(
        mut self,
        entity_id: impl Into<crate::components::ChronicleEntityId>,
    ) -> Self {
        self.entity_id = try_serialize_field(Self::descriptor_entity_id(), [entity_id]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::ChronicleEntityId`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_entity_id`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_entity_id(
        mut self,
        entity_id: impl IntoIterator<Item = impl Into<crate::components::ChronicleEntityId>>,
    ) -> Self {
        self.entity_id = try_serialize_field(Self::descriptor_entity_id(), entity_id);
        self
    }
}

impl ::re_byte_size::SizeBytes for ChronicleEntityRef {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.entity_type.heap_size_bytes() + self.entity_id.heap_size_bytes()
    }
}
