// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/chronicle_event.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: A Chronicle SaaS event with source, type, and optional JSON payload.
///
/// Events are the core data type in Chronicle. Each event represents a
/// single occurrence from a SaaS source (e.g. a Stripe payment, a support
/// ticket, a product page view). Events are logged at entity paths that
/// encode the entity hierarchy: `/{org}/{entity_type}/{entity_id}/{source}/{event_type}`.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct ChronicleEvent {
    /// The data source (e.g. "stripe", "support", "product", "marketing").
    pub source: Option<SerializedComponentBatch>,

    /// The event type (e.g. "payment_intent.succeeded", "ticket.created").
    pub event_type: Option<SerializedComponentBatch>,

    /// The topic/category (e.g. "payments", "tickets", "usage").
    pub topic: Option<SerializedComponentBatch>,

    /// JSON payload serialized as a string.
    pub payload: Option<SerializedComponentBatch>,

    /// Optional color for the event marker.
    pub color: Option<SerializedComponentBatch>,

    /// Optional text label.
    pub label: Option<SerializedComponentBatch>,
}

impl ChronicleEvent {
    /// Returns the [`ComponentDescriptor`] for [`Self::source`].
    ///
    /// The corresponding component is [`crate::components::ChronicleSource`].
    #[inline]
    pub fn descriptor_source() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.ChronicleEvent".into()),
            component: "ChronicleEvent:source".into(),
            component_type: Some("rerun.components.ChronicleSource".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::event_type`].
    ///
    /// The corresponding component is [`crate::components::ChronicleEventType`].
    #[inline]
    pub fn descriptor_event_type() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.ChronicleEvent".into()),
            component: "ChronicleEvent:event_type".into(),
            component_type: Some("rerun.components.ChronicleEventType".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::topic`].
    ///
    /// The corresponding component is [`crate::components::ChronicleTopic`].
    #[inline]
    pub fn descriptor_topic() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.ChronicleEvent".into()),
            component: "ChronicleEvent:topic".into(),
            component_type: Some("rerun.components.ChronicleTopic".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::payload`].
    ///
    /// The corresponding component is [`crate::components::ChroniclePayload`].
    #[inline]
    pub fn descriptor_payload() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.ChronicleEvent".into()),
            component: "ChronicleEvent:payload".into(),
            component_type: Some("rerun.components.ChroniclePayload".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::color`].
    ///
    /// The corresponding component is [`crate::components::Color`].
    #[inline]
    pub fn descriptor_color() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.ChronicleEvent".into()),
            component: "ChronicleEvent:color".into(),
            component_type: Some("rerun.components.Color".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::label`].
    ///
    /// The corresponding component is [`crate::components::Text`].
    #[inline]
    pub fn descriptor_label() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.ChronicleEvent".into()),
            component: "ChronicleEvent:label".into(),
            component_type: Some("rerun.components.Text".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| {
        [
            ChronicleEvent::descriptor_source(),
            ChronicleEvent::descriptor_event_type(),
        ]
    });

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [ChronicleEvent::descriptor_topic()]);

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 3usize]> =
    std::sync::LazyLock::new(|| {
        [
            ChronicleEvent::descriptor_payload(),
            ChronicleEvent::descriptor_color(),
            ChronicleEvent::descriptor_label(),
        ]
    });

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 6usize]> =
    std::sync::LazyLock::new(|| {
        [
            ChronicleEvent::descriptor_source(),
            ChronicleEvent::descriptor_event_type(),
            ChronicleEvent::descriptor_topic(),
            ChronicleEvent::descriptor_payload(),
            ChronicleEvent::descriptor_color(),
            ChronicleEvent::descriptor_label(),
        ]
    });

impl ChronicleEvent {
    /// The total number of components in the archetype: 2 required, 1 recommended, 3 optional
    pub const NUM_COMPONENTS: usize = 6usize;
}

impl ::re_types_core::Archetype for ChronicleEvent {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.archetypes.ChronicleEvent".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Chronicle event"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let source = arrays_by_descr
            .get(&Self::descriptor_source())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_source()));
        let event_type = arrays_by_descr
            .get(&Self::descriptor_event_type())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_event_type())
            });
        let topic = arrays_by_descr
            .get(&Self::descriptor_topic())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_topic()));
        let payload = arrays_by_descr
            .get(&Self::descriptor_payload())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_payload()));
        let color = arrays_by_descr
            .get(&Self::descriptor_color())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_color()));
        let label = arrays_by_descr
            .get(&Self::descriptor_label())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_label()));
        Ok(Self {
            source,
            event_type,
            topic,
            payload,
            color,
            label,
        })
    }
}

impl ::re_types_core::AsComponents for ChronicleEvent {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            self.source.clone(),
            self.event_type.clone(),
            self.topic.clone(),
            self.payload.clone(),
            self.color.clone(),
            self.label.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for ChronicleEvent {}

impl crate::VisualizableArchetype for ChronicleEvent {
    #[inline]
    fn visualizer(&self) -> crate::Visualizer {
        crate::Visualizer::new("ChronicleEvent").with_overrides(self)
    }
}

impl ChronicleEvent {
    /// Create a new `ChronicleEvent`.
    #[inline]
    pub fn new(
        source: impl Into<crate::components::ChronicleSource>,
        event_type: impl Into<crate::components::ChronicleEventType>,
    ) -> Self {
        Self {
            source: try_serialize_field(Self::descriptor_source(), [source]),
            event_type: try_serialize_field(Self::descriptor_event_type(), [event_type]),
            topic: None,
            payload: None,
            color: None,
            label: None,
        }
    }

    /// Update only some specific fields of a `ChronicleEvent`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `ChronicleEvent`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            source: Some(SerializedComponentBatch::new(
                crate::components::ChronicleSource::arrow_empty(),
                Self::descriptor_source(),
            )),
            event_type: Some(SerializedComponentBatch::new(
                crate::components::ChronicleEventType::arrow_empty(),
                Self::descriptor_event_type(),
            )),
            topic: Some(SerializedComponentBatch::new(
                crate::components::ChronicleTopic::arrow_empty(),
                Self::descriptor_topic(),
            )),
            payload: Some(SerializedComponentBatch::new(
                crate::components::ChroniclePayload::arrow_empty(),
                Self::descriptor_payload(),
            )),
            color: Some(SerializedComponentBatch::new(
                crate::components::Color::arrow_empty(),
                Self::descriptor_color(),
            )),
            label: Some(SerializedComponentBatch::new(
                crate::components::Text::arrow_empty(),
                Self::descriptor_label(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.source
                .map(|source| source.partitioned(_lengths.clone()))
                .transpose()?,
            self.event_type
                .map(|event_type| event_type.partitioned(_lengths.clone()))
                .transpose()?,
            self.topic
                .map(|topic| topic.partitioned(_lengths.clone()))
                .transpose()?,
            self.payload
                .map(|payload| payload.partitioned(_lengths.clone()))
                .transpose()?,
            self.color
                .map(|color| color.partitioned(_lengths.clone()))
                .transpose()?,
            self.label
                .map(|label| label.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_source = self.source.as_ref().map(|b| b.array.len());
        let len_event_type = self.event_type.as_ref().map(|b| b.array.len());
        let len_topic = self.topic.as_ref().map(|b| b.array.len());
        let len_payload = self.payload.as_ref().map(|b| b.array.len());
        let len_color = self.color.as_ref().map(|b| b.array.len());
        let len_label = self.label.as_ref().map(|b| b.array.len());
        let len = None
            .or(len_source)
            .or(len_event_type)
            .or(len_topic)
            .or(len_payload)
            .or(len_color)
            .or(len_label)
            .unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// The data source (e.g. "stripe", "support", "product", "marketing").
    #[inline]
    pub fn with_source(mut self, source: impl Into<crate::components::ChronicleSource>) -> Self {
        self.source = try_serialize_field(Self::descriptor_source(), [source]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::ChronicleSource`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_source`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_source(
        mut self,
        source: impl IntoIterator<Item = impl Into<crate::components::ChronicleSource>>,
    ) -> Self {
        self.source = try_serialize_field(Self::descriptor_source(), source);
        self
    }

    /// The event type (e.g. "payment_intent.succeeded", "ticket.created").
    #[inline]
    pub fn with_event_type(
        mut self,
        event_type: impl Into<crate::components::ChronicleEventType>,
    ) -> Self {
        self.event_type = try_serialize_field(Self::descriptor_event_type(), [event_type]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::ChronicleEventType`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_event_type`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_event_type(
        mut self,
        event_type: impl IntoIterator<Item = impl Into<crate::components::ChronicleEventType>>,
    ) -> Self {
        self.event_type = try_serialize_field(Self::descriptor_event_type(), event_type);
        self
    }

    /// The topic/category (e.g. "payments", "tickets", "usage").
    #[inline]
    pub fn with_topic(mut self, topic: impl Into<crate::components::ChronicleTopic>) -> Self {
        self.topic = try_serialize_field(Self::descriptor_topic(), [topic]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::ChronicleTopic`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_topic`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_topic(
        mut self,
        topic: impl IntoIterator<Item = impl Into<crate::components::ChronicleTopic>>,
    ) -> Self {
        self.topic = try_serialize_field(Self::descriptor_topic(), topic);
        self
    }

    /// JSON payload serialized as a string.
    #[inline]
    pub fn with_payload(mut self, payload: impl Into<crate::components::ChroniclePayload>) -> Self {
        self.payload = try_serialize_field(Self::descriptor_payload(), [payload]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::ChroniclePayload`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_payload`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_payload(
        mut self,
        payload: impl IntoIterator<Item = impl Into<crate::components::ChroniclePayload>>,
    ) -> Self {
        self.payload = try_serialize_field(Self::descriptor_payload(), payload);
        self
    }

    /// Optional color for the event marker.
    #[inline]
    pub fn with_color(mut self, color: impl Into<crate::components::Color>) -> Self {
        self.color = try_serialize_field(Self::descriptor_color(), [color]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Color`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_color`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_color(
        mut self,
        color: impl IntoIterator<Item = impl Into<crate::components::Color>>,
    ) -> Self {
        self.color = try_serialize_field(Self::descriptor_color(), color);
        self
    }

    /// Optional text label.
    #[inline]
    pub fn with_label(mut self, label: impl Into<crate::components::Text>) -> Self {
        self.label = try_serialize_field(Self::descriptor_label(), [label]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Text`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_label`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_label(
        mut self,
        label: impl IntoIterator<Item = impl Into<crate::components::Text>>,
    ) -> Self {
        self.label = try_serialize_field(Self::descriptor_label(), label);
        self
    }
}

impl ::re_byte_size::SizeBytes for ChronicleEvent {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.source.heap_size_bytes()
            + self.event_type.heap_size_bytes()
            + self.topic.heap_size_bytes()
            + self.payload.heap_size_bytes()
            + self.color.heap_size_bytes()
            + self.label.heap_size_bytes()
    }
}
